import './components/header-fixed'
import './components/lang';
import './components/accordion';
import './components/members-slider';
import './components/validate-feedback-form';
import './components/validate-request-form';
import './components/adapt';
import './components/plyr';
import './components/show-more';
import './components/map';
import './components/tabs';
import './components/goodshare';
import './components/similar-slider';
import './components/dotted-map';